# Generated by Django 4.0.3 on 2022-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_postviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='IPAddress',
            field=models.GenericIPAddressField(default='45.243.82.169'),
        ),
    ]
