# Generated by Django 4.0.3 on 2022-04-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_postviews_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
