# Generated by Django 4.0.3 on 2022-06-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_posthit_post_hits_posthit_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
    ]
