# Generated by Django 5.2.1 on 2025-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس مقاله'),
        ),
    ]
